In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('insurance.csv')

In [3]:
df1 = df.copy()
df2 = df.copy()
df3 = df.copy()
df4 = df.copy()
df5 = df.copy()

In [4]:
df1.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Label Encoder using manual approach

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df['sex'] = le.fit_transform(df['sex'])

In [8]:
df['smoker'] = le.fit_transform(df['smoker'])

In [9]:
df['region'] = le.fit_transform(df['region'])

In [10]:
df.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# Label encoder using for loop

In [11]:
df1.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [12]:
from pandas.core.dtypes.common import is_numeric_dtype

In [13]:
for col in df1.columns:
    if is_numeric_dtype(df1[col]):
        continue
    else:
        df1[col] = le.fit_transform(df1[col])

In [14]:
df1.head()

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

# One hot Encoder using manual approach

In [15]:
df2.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [16]:
dummy = pd.get_dummies(df2['sex'],drop_first=True,prefix='gender')   #df2['sex'] = df2.sex

In [17]:
dummy.head()

gender_male
0            0
1            1
2            1
3            1
4            1

In [18]:
dummy1 = pd.get_dummies(df2.smoker,drop_first=True,prefix='smoker')
dummy1.head()

smoker_yes
0           1
1           0
2           0
3           0
4           0

In [19]:
dummy2 = pd.get_dummies(df2['region'],drop_first=True,prefix='region')
dummy2.head()

region_northwest  region_southeast  region_southwest
0                 0                 0                 1
1                 0                 1                 0
2                 0                 1                 0
3                 1                 0                 0
4                 1                 0                 0

In [20]:
df2.drop(columns= ['sex','smoker','region'],inplace=True)
df2.head()

age     bmi  children      charges
0   19  27.900         0  16884.92400
1   18  33.770         1   1725.55230
2   28  33.000         3   4449.46200
3   33  22.705         0  21984.47061
4   32  28.880         0   3866.85520

In [21]:
df2 = pd.concat([df2,dummy,dummy1,dummy2],axis = 1)

In [22]:
df2.head()

age     bmi  children      charges  gender_male  smoker_yes  \
0   19  27.900         0  16884.92400            0           1   
1   18  33.770         1   1725.55230            1           0   
2   28  33.000         3   4449.46200            1           0   
3   33  22.705         0  21984.47061            1           0   
4   32  28.880         0   3866.85520            1           0   

   region_northwest  region_southeast  region_southwest  
0                 0                 0                 1  
1                 0                 1                 0  
2                 0                 1                 0  
3                 1                 0                 0  
4                 1                 0                 0

# One hot encoding using for loop

In [23]:
df3.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [24]:
for col in df3.columns:
    if is_numeric_dtype(df3[col]):
        continue
    else:
        dummy3 = pd.get_dummies(df3[col],drop_first=True,prefix = col)
        df3.drop(col,axis=1,inplace = True)
        df3 = pd.concat([df3,dummy3],axis = 1)
df3.head()
        

age     bmi  children      charges  sex_male  smoker_yes  region_northwest  \
0   19  27.900         0  16884.92400         0           1                 0   
1   18  33.770         1   1725.55230         1           0                 0   
2   28  33.000         3   4449.46200         1           0                 0   
3   33  22.705         0  21984.47061         1           0                 1   
4   32  28.880         0   3866.85520         1           0                 1   

   region_southeast  region_southwest  
0                 0                 1  
1                 1                 0  
2                 1                 0  
3                 0                 0  
4                 0                 0

# Ordinal Encoder using manual approach

In [25]:
df4.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [26]:
from sklearn.preprocessing import OrdinalEncoder

In [27]:
sex_order = df4.sex.unique()
sex_order

array(['female', 'male'], dtype=object)

In [28]:
ordinal = OrdinalEncoder(categories=[sex_order])
ordinal

OrdinalEncoder(categories=[array(['female', 'male'], dtype=object)])

In [29]:
encoded = ordinal.fit_transform(df4[['sex']])
encoded

array([[0.],
       [1.],
       [1.],
       ...,
       [0.],
       [0.],
       [0.]])

In [30]:
df4['sex'] = pd.DataFrame(encoded,columns = ['SEX'])
df4.head()

age  sex     bmi  children smoker     region      charges
0   19  0.0  27.900         0    yes  southwest  16884.92400
1   18  1.0  33.770         1     no  southeast   1725.55230
2   28  1.0  33.000         3     no  southeast   4449.46200
3   33  1.0  22.705         0     no  northwest  21984.47061
4   32  1.0  28.880         0     no  northwest   3866.85520

In [31]:
smoker_order = df4.smoker.unique()
smoker_order

array(['yes', 'no'], dtype=object)

In [32]:
ordinal = OrdinalEncoder(categories=[smoker_order])
ordinal

OrdinalEncoder(categories=[array(['yes', 'no'], dtype=object)])

In [33]:
encoded = ordinal.fit_transform(df4[['smoker']])
encoded

array([[0.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [0.]])

In [34]:
df4['smoker'] = pd.DataFrame(encoded,columns=['SMOKER'])
df4.head()

age  sex     bmi  children  smoker     region      charges
0   19  0.0  27.900         0     0.0  southwest  16884.92400
1   18  1.0  33.770         1     1.0  southeast   1725.55230
2   28  1.0  33.000         3     1.0  southeast   4449.46200
3   33  1.0  22.705         0     1.0  northwest  21984.47061
4   32  1.0  28.880         0     1.0  northwest   3866.85520

In [35]:
region_order = df4.region.unique()
region_order

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [36]:
ordinal = OrdinalEncoder(categories=[region_order])
ordinal

OrdinalEncoder(categories=[array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)])

In [37]:
encoded = ordinal.fit_transform(df4[['region']])
encoded

array([[0.],
       [1.],
       [1.],
       ...,
       [1.],
       [0.],
       [2.]])

In [38]:
df4['region'] = pd.DataFrame(encoded,columns = ['REGION'])
df4.head()

age  sex     bmi  children  smoker  region      charges
0   19  0.0  27.900         0     0.0     0.0  16884.92400
1   18  1.0  33.770         1     1.0     1.0   1725.55230
2   28  1.0  33.000         3     1.0     1.0   4449.46200
3   33  1.0  22.705         0     1.0     2.0  21984.47061
4   32  1.0  28.880         0     1.0     2.0   3866.85520

# Ordinal encoder using for loop

In [39]:
df5.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [40]:
for col in df5.columns:
    if is_numeric_dtype(df5[col]):
        continue
    else:
        order = df5[col].unique()
        ordinal = OrdinalEncoder(categories=[order])
        encoded = ordinal.fit_transform(df5[[col]])
        df5[col] = pd.DataFrame(encoded,columns=[col])
df5.head()

age  sex     bmi  children  smoker  region      charges
0   19  0.0  27.900         0     0.0     0.0  16884.92400
1   18  1.0  33.770         1     1.0     1.0   1725.55230
2   28  1.0  33.000         3     1.0     1.0   4449.46200
3   33  1.0  22.705         0     1.0     2.0  21984.47061
4   32  1.0  28.880         0     1.0     2.0   3866.85520