In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

# Step 01 - Regression

In [8]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [9]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [10]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [11]:
#importing train test splitting libraries
from sklearn.model_selection import train_test_split

In [12]:
#splitting the dataset according to instructed training and testing size
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=.30,random_state = 1)

In [13]:
xtrain.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [14]:
ytrain.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [15]:
#importing the linear regression model from sklearn library
from sklearn.linear_model import LinearRegression

In [16]:
#creating object for the LR model
lr = LinearRegression()

In [17]:
#fitting the model with training datasets
lr.fit(xtrain,ytrain)

LinearRegression()

In [25]:
#predicting 'y' for the features x1 and x2 automatically
lr.predict([[1,72.385301]])

array([[206.84955312]])

In [27]:
#testing accuracy of the model
lr.score(xtest,ytest)

0.905995960709116

In [29]:
#training accuracy of the model
lr.score(xtrain,ytrain)

0.8972135459668118

In [31]:
#MSE importing
from sklearn.metrics import mean_squared_error

In [37]:
#MSE for testing
test_mse = mean_squared_error(ytest,lr.predict(xtest))
mse

99.67250998070031

In [39]:
#MSE for training
train_mse = mean_squared_error(ytrain,lr.predict(xtrain))
train_mse

104.03843190905903

# Applying KNN regressor

In [40]:
xtrain.head()

Gender     Height
1277       1  72.385301
5361       0  60.960147
5728       0  69.119292
4276       1  68.271050
3112       1  64.991405

In [41]:
ytrain.head()

Weight
1277  189.165592
5361  124.876796
5728  168.864403
4276  172.941248
3112  144.551044

In [42]:
#importing KNeighborsRegressor model from sklearn
from sklearn.neighbors import KNeighborsRegressor

In [44]:
knnr = KNeighborsRegressor()

In [45]:
knnr.fit(xtrain,ytrain)

KNeighborsRegressor()

In [47]:
knnr.predict([[0,60.960147]])

array([[121.12435126]])

In [49]:
#training accuracy of knn regressor
knnr.score(xtrain,ytrain)

0.9170756955071054

In [51]:
#testing accuracy of knn regressor
knnr.score(xtest,ytest)

0.8838502073708883

In [55]:
#MSE for training the model KNN regressor
mse_train = mean_squared_error(ytrain,knnr.predict(xtrain))
mse_train

83.93435387706295

In [56]:
#MSE for testing the model KNN regressor
mse_test = mean_squared_error(ytest,knnr.predict(xtest))
mse_test

123.15365863436983

# Comparing the KNN regressor with Linear regressor

In [67]:
print('Training accuracy of KNN regressor',knnr.score(xtrain,ytrain))
print('Testing accuracy of knn regressor',knnr.score(xtest,ytest))
print('MSE for training the model KNN regressor',mse_train)
print('MSE for testing the model KNN regressor',mse_test)

print()

print('Training accuracy of Linear regression',lr.score(xtrain,ytrain))
print('Testing accuracy of Linear regression',lr.score(xtest,ytest))
print('MSE for training the model Linear regression',train_mse)
print('MSE for testing the model Linear regression',test_mse)


Training accuracy of KNN regressor 0.9170756955071054
Testing accuracy of knn regressor 0.8838502073708883
MSE for training the model KNN regressor 83.93435387706295
MSE for testing the model KNN regressor 123.15365863436983

Training accuracy of Linear regression 0.8972135459668118
Testing accuracy of Linear regression 0.905995960709116
MSE for training the model Linear regression 104.03843190905903
MSE for testing the model Linear regression 99.67250998070031


# Step 02 - Classification

In [68]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [69]:
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [70]:
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [71]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size= .3,random_state=2)

In [72]:
xtrain.head()

Height      Weight
1757  68.423586  178.620033
7389  59.368139  118.764518
6944  64.121065  146.801099
6362  62.059680  122.197037
6438  65.736057  139.640355

In [73]:
ytrain.head()

Gender
1757       1
7389       0
6944       0
6362       0
6438       0

In [74]:
#importing KNN classifier
from sklearn.neighbors import KNeighborsClassifier

In [75]:
knnc = KNeighborsClassifier()

In [76]:
#fitting the model with training data
knnc.fit(xtrain,ytrain)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [78]:
knnc.predict([[59.368139,118.764518]])

array([0], dtype=int64)

In [79]:
#training accuracy of KNN classifier
knnc.score(xtrain,ytrain)

0.9303607214428857

In [80]:
knnc.score(xtest,ytest)

0.9092325671990651